/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalgrupo9.vistas;

import java.awt.Color;

/**
 *
 * @author Maxi
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jListarCuartel = new javax.swing.JMenu();
        jMGestionarCuartel = new javax.swing.JMenuItem();
        jBrigadas = new javax.swing.JMenu();
        jMGestionarBrigada = new javax.swing.JMenuItem();
        jBomberos = new javax.swing.JMenu();
        jMGestionarBombero = new javax.swing.JMenuItem();
        jSiniestros = new javax.swing.JMenu();
        jMGestionarSiniestro = new javax.swing.JMenuItem();
        jConsulta = new javax.swing.JMenu();
        jCCuarteles = new javax.swing.JMenuItem();
        jCBrigadas = new javax.swing.JMenuItem();
        jCSiniestros = new javax.swing.JMenuItem();
        jSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        jListarCuartel.setText("Cuarteles");
        jListarCuartel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListarCuartelActionPerformed(evt);
            }
        });

        jMGestionarCuartel.setText("Gestionar Cuartel");
        jMGestionarCuartel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGestionarCuartelActionPerformed(evt);
            }
        });
        jListarCuartel.add(jMGestionarCuartel);

        jMenuBar1.add(jListarCuartel);

        jBrigadas.setText("Brigadas");

        jMGestionarBrigada.setText("Gestionar Brigada");
        jMGestionarBrigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGestionarBrigadaActionPerformed(evt);
            }
        });
        jBrigadas.add(jMGestionarBrigada);

        jMenuBar1.add(jBrigadas);

        jBomberos.setText("Bomberos");

        jMGestionarBombero.setText("Gestionar Bombero");
        jMGestionarBombero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGestionarBomberoActionPerformed(evt);
            }
        });
        jBomberos.add(jMGestionarBombero);

        jMenuBar1.add(jBomberos);

        jSiniestros.setText("Siniestros");

        jMGestionarSiniestro.setText("Gestionar Siniestro");
        jMGestionarSiniestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGestionarSiniestroActionPerformed(evt);
            }
        });
        jSiniestros.add(jMGestionarSiniestro);

        jMenuBar1.add(jSiniestros);

        jConsulta.setText("Consultas");
        jConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jConsultaMouseClicked(evt);
            }
        });
        jConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultaActionPerformed(evt);
            }
        });

        jCCuarteles.setText("Cuarteles");
        jCCuarteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCuartelesActionPerformed(evt);
            }
        });
        jConsulta.add(jCCuarteles);

        jCBrigadas.setText("Brigadas");
        jCBrigadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBrigadasActionPerformed(evt);
            }
        });
        jConsulta.add(jCBrigadas);

        jCSiniestros.setText("Siniestros");
        jCSiniestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCSiniestrosActionPerformed(evt);
            }
        });
        jConsulta.add(jCSiniestros);

        jMenuBar1.add(jConsulta);

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // GESTIONAR CUARTEL
    private void jMGestionarCuartelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGestionarCuartelActionPerformed

        escritorio.removeAll();
        escritorio.repaint();
        GestionarCuartel GC = new GestionarCuartel();
        GC.setVisible(true);
        GC.getContentPane().setBackground(Color.white);
        escritorio.add(GC);


    }//GEN-LAST:event_jMGestionarCuartelActionPerformed
//-------------------------------------------------------------------------------------------

    //GESTIONAR BRIGADA
    private void jMGestionarBrigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGestionarBrigadaActionPerformed

        escritorio.removeAll();
        escritorio.repaint();
        GestionarBrigada GB = new GestionarBrigada();
        GB.setVisible(true);
        GB.getContentPane().setBackground(Color.white);
        escritorio.add(GB);
    }//GEN-LAST:event_jMGestionarBrigadaActionPerformed

//-------------------------------------------------------------------------------------------
    //GESTIONAR BOMBERO
    private void jMGestionarBomberoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGestionarBomberoActionPerformed

        escritorio.removeAll();
        escritorio.repaint();
        GestionarBombero GBom = new GestionarBombero();
        GBom.setVisible(true);
        GBom.getContentPane().setBackground(Color.white);
        escritorio.add(GBom);
    }//GEN-LAST:event_jMGestionarBomberoActionPerformed
//-------------------------------------------------------------------------------------------
    //GESTIONAR SINIESTRO
    private void jMGestionarSiniestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGestionarSiniestroActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        GestionarSiniestros GS = new GestionarSiniestros();
        GS.setVisible(true);
        GS.getContentPane().setBackground(Color.white);
        escritorio.add(GS);
    }//GEN-LAST:event_jMGestionarSiniestroActionPerformed
//-------------------------------------------------------------------------------------------
    //LISTA DE CUARTELES (YA NO SE USA)
    private void jListarCuartelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListarCuartelActionPerformed
    }//GEN-LAST:event_jListarCuartelActionPerformed

    private void jConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultaActionPerformed
        
    }//GEN-LAST:event_jConsultaActionPerformed

    private void jConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jConsultaMouseClicked
        
        

    }//GEN-LAST:event_jConsultaMouseClicked

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        
        dispose();
        
    }//GEN-LAST:event_jSalirActionPerformed

    private void jCCuartelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCuartelesActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        
        ConsultarCuartel cc = new ConsultarCuartel();
        
        cc.setVisible(true);
        
        cc.getContentPane().setBackground(Color.white);
        
        escritorio.add(cc);
        
    }//GEN-LAST:event_jCCuartelesActionPerformed

    private void jCBrigadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBrigadasActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        
        ConsultarBrigada cb = new ConsultarBrigada();
        
        cb.setVisible(true);
        
        cb.getContentPane().setBackground(Color.white);
        
        escritorio.add(cb);
        
    }//GEN-LAST:event_jCBrigadasActionPerformed

    private void jCSiniestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCSiniestrosActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        
        ConsultarSiniestro cs = new ConsultarSiniestro();
        
        cs.setVisible(true);
        
        cs.getContentPane().setBackground(Color.white);
        
        escritorio.add(cs);
        
    }//GEN-LAST:event_jCSiniestrosActionPerformed
//-------------------------------------------------------------------------------------------

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jBomberos;
    private javax.swing.JMenu jBrigadas;
    private javax.swing.JMenuItem jCBrigadas;
    private javax.swing.JMenuItem jCCuarteles;
    private javax.swing.JMenuItem jCSiniestros;
    private javax.swing.JMenu jConsulta;
    private javax.swing.JMenu jListarCuartel;
    private javax.swing.JMenuItem jMGestionarBombero;
    private javax.swing.JMenuItem jMGestionarBrigada;
    private javax.swing.JMenuItem jMGestionarCuartel;
    private javax.swing.JMenuItem jMGestionarSiniestro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jSalir;
    private javax.swing.JMenu jSiniestros;
    // End of variables declaration//GEN-END:variables
}
